version: "3"
services:
  app:
    build: ./docker/app
    ports:
      - 80:5000
    environment:
      - MYSQL_DATA_BASE=app
      - MYSQL_USER=flask
      - MYSQL_PASSWORD=flask
    volumes:
      - ./app:/app
    command: python /app/main.py
    depends_on: 
      - db

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: flask
      MYSQL_PASSWORD: flask
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/log:/var/log/mysql
    # command: mysql --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    image: phpmyadmin:5.2
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 4040:80
    depends_on:
      - db
